### ISSUE TITLE
normFit on matrix object

### ISSUE THREAD

**Issue by alievakrash** [hredestig/crmn#1]
Hello,

I am trying to make a normalization model on a matrix object but it seems that I am missing some argument and I can not figure out which one.

Here is what I tried:
>nfit <- normFit(G, "crmn", factor=G, ncomp=2)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'mexprs': unable to find an inherited method for function ‘analytes’ for signature ‘"matrix", "missing"’

Not sure what and how should I specify for 'mexprs' and 'analytes'.

Here is my example dataset:
https://we.tl/t-p6EHQYcqSG

Cheers,

Maria

**Comment by hredestig** [comment]
Sorry for the extremely slow response. If  `G` is a matrix as in your case, then you have to also pass the `standards` argument (list of True/False for selecting the columns in G that are internal standards). See documentation and examples in `normFit`  Above, since you don't pass `standards` `G` is evaluated as an `ExpressionSet` which then fails.
